instances:
  - ip: "192.168.1.1"
    name: "instance-1"
    labels:
      env: "production"
      role: "web"
  - ip: "192.168.1.2"
    name: "instance-2"
    labels:
      env: "production"
      role: "web"
  - ip: "192.168.1.3"
    name: "instance-3"
    labels:
      env: "production"
      role: "web"
  - ip: "192.168.1.4"
    name: "instance-4"
    labels:
      env: "dev"
      role: "web"