// Code generated by MockGen. DO NOT EDIT.
// Source: rolling_deployment.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	inventory "github.com/xnok/dides/internal/inventory"
)

// MockInventoryService is a mock of InventoryService interface.
type MockInventoryService struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceMockRecorder
}

// MockInventoryServiceMockRecorder is the mock recorder for MockInventoryService.
type MockInventoryServiceMockRecorder struct {
	mock *MockInventoryService
}

// NewMockInventoryService creates a new mock instance.
func NewMockInventoryService(ctrl *gomock.Controller) *MockInventoryService {
	mock := &MockInventoryService{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService) EXPECT() *MockInventoryServiceMockRecorder {
	return m.recorder
}

// CountByLabels mocks base method.
func (m *MockInventoryService) CountByLabels(ctx context.Context, labels map[string]string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByLabels", ctx, labels)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByLabels indicates an expected call of CountByLabels.
func (mr *MockInventoryServiceMockRecorder) CountByLabels(ctx, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByLabels", reflect.TypeOf((*MockInventoryService)(nil).CountByLabels), ctx, labels)
}

// CountCompleted mocks base method.
func (m *MockInventoryService) CountCompleted(ctx context.Context, labels map[string]string, desiredState inventory.State) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCompleted", ctx, labels, desiredState)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCompleted indicates an expected call of CountCompleted.
func (mr *MockInventoryServiceMockRecorder) CountCompleted(ctx, labels, desiredState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCompleted", reflect.TypeOf((*MockInventoryService)(nil).CountCompleted), ctx, labels, desiredState)
}

// CountFailed mocks base method.
func (m *MockInventoryService) CountFailed(ctx context.Context, labels map[string]string, desiredState inventory.State) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFailed", ctx, labels, desiredState)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFailed indicates an expected call of CountFailed.
func (mr *MockInventoryServiceMockRecorder) CountFailed(ctx, labels, desiredState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFailed", reflect.TypeOf((*MockInventoryService)(nil).CountFailed), ctx, labels, desiredState)
}

// CountInProgress mocks base method.
func (m *MockInventoryService) CountInProgress(ctx context.Context, labels map[string]string, desiredState inventory.State) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInProgress", ctx, labels, desiredState)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInProgress indicates an expected call of CountInProgress.
func (mr *MockInventoryServiceMockRecorder) CountInProgress(ctx, labels, desiredState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInProgress", reflect.TypeOf((*MockInventoryService)(nil).CountInProgress), ctx, labels, desiredState)
}

// CountNeedingUpdate mocks base method.
func (m *MockInventoryService) CountNeedingUpdate(ctx context.Context, labels map[string]string, desiredState inventory.State) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNeedingUpdate", ctx, labels, desiredState)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNeedingUpdate indicates an expected call of CountNeedingUpdate.
func (mr *MockInventoryServiceMockRecorder) CountNeedingUpdate(ctx, labels, desiredState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNeedingUpdate", reflect.TypeOf((*MockInventoryService)(nil).CountNeedingUpdate), ctx, labels, desiredState)
}

// GetInstancesByLabels mocks base method.
func (m *MockInventoryService) GetInstancesByLabels(ctx context.Context, labels map[string]string) ([]*inventory.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstancesByLabels", ctx, labels)
	ret0, _ := ret[0].([]*inventory.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstancesByLabels indicates an expected call of GetInstancesByLabels.
func (mr *MockInventoryServiceMockRecorder) GetInstancesByLabels(ctx, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstancesByLabels", reflect.TypeOf((*MockInventoryService)(nil).GetInstancesByLabels), ctx, labels)
}

// GetNeedingUpdate mocks base method.
func (m *MockInventoryService) GetNeedingUpdate(ctx context.Context, labels map[string]string, desiredState inventory.State, opts *inventory.GetNeedingUpdateOptions) ([]*inventory.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNeedingUpdate", ctx, labels, desiredState, opts)
	ret0, _ := ret[0].([]*inventory.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNeedingUpdate indicates an expected call of GetNeedingUpdate.
func (mr *MockInventoryServiceMockRecorder) GetNeedingUpdate(ctx, labels, desiredState, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNeedingUpdate", reflect.TypeOf((*MockInventoryService)(nil).GetNeedingUpdate), ctx, labels, desiredState, opts)
}

// ResetFailedInstances mocks base method.
func (m *MockInventoryService) ResetFailedInstances(ctx context.Context, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedInstances", ctx, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedInstances indicates an expected call of ResetFailedInstances.
func (mr *MockInventoryServiceMockRecorder) ResetFailedInstances(ctx, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedInstances", reflect.TypeOf((*MockInventoryService)(nil).ResetFailedInstances), ctx, labels)
}

// UpdateDesiredState mocks base method.
func (m *MockInventoryService) UpdateDesiredState(ctx context.Context, instanceKey string, state inventory.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDesiredState", ctx, instanceKey, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDesiredState indicates an expected call of UpdateDesiredState.
func (mr *MockInventoryServiceMockRecorder) UpdateDesiredState(ctx, instanceKey, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDesiredState", reflect.TypeOf((*MockInventoryService)(nil).UpdateDesiredState), ctx, instanceKey, state)
}
