// Code generated by MockGen. DO NOT EDIT.
// Source: strategy.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	deployment "github.com/xnok/dides/internal/deployment"
)

// MockDeploymentStrategy is a mock of DeploymentStrategy interface.
type MockDeploymentStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentStrategyMockRecorder
}

// MockDeploymentStrategyMockRecorder is the mock recorder for MockDeploymentStrategy.
type MockDeploymentStrategyMockRecorder struct {
	mock *MockDeploymentStrategy
}

// NewMockDeploymentStrategy creates a new mock instance.
func NewMockDeploymentStrategy(ctrl *gomock.Controller) *MockDeploymentStrategy {
	mock := &MockDeploymentStrategy{ctrl: ctrl}
	mock.recorder = &MockDeploymentStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentStrategy) EXPECT() *MockDeploymentStrategyMockRecorder {
	return m.recorder
}

// IsFailureThresholdExceeded mocks base method.
func (m *MockDeploymentStrategy) IsFailureThresholdExceeded(record *deployment.DeploymentRecord) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFailureThresholdExceeded", record)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFailureThresholdExceeded indicates an expected call of IsFailureThresholdExceeded.
func (mr *MockDeploymentStrategyMockRecorder) IsFailureThresholdExceeded(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFailureThresholdExceeded", reflect.TypeOf((*MockDeploymentStrategy)(nil).IsFailureThresholdExceeded), record)
}

// ProgressDeployment mocks base method.
func (m *MockDeploymentStrategy) ProgressDeployment(ctx context.Context, record *deployment.DeploymentRecord) (*deployment.DeploymentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProgressDeployment", ctx, record)
	ret0, _ := ret[0].(*deployment.DeploymentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProgressDeployment indicates an expected call of ProgressDeployment.
func (mr *MockDeploymentStrategyMockRecorder) ProgressDeployment(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProgressDeployment", reflect.TypeOf((*MockDeploymentStrategy)(nil).ProgressDeployment), ctx, record)
}

// RollbackDeployment mocks base method.
func (m *MockDeploymentStrategy) RollbackDeployment(record *deployment.DeploymentRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackDeployment", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackDeployment indicates an expected call of RollbackDeployment.
func (mr *MockDeploymentStrategyMockRecorder) RollbackDeployment(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackDeployment", reflect.TypeOf((*MockDeploymentStrategy)(nil).RollbackDeployment), record)
}

// StartDeployment mocks base method.
func (m *MockDeploymentStrategy) StartDeployment(record *deployment.DeploymentRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDeployment", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDeployment indicates an expected call of StartDeployment.
func (mr *MockDeploymentStrategyMockRecorder) StartDeployment(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDeployment", reflect.TypeOf((*MockDeploymentStrategy)(nil).StartDeployment), record)
}
